### PR TITLE
LPS-0 DO NOT MERGE Run all forms tests

### PR DESCRIPTION
**Pull request by pedroqueiroz**

### CODE REVIEW

**Comment by pedroqueiroz** [comment]
ci:test

**Comment by clovisdasilvaneto** [comment]
Hey @alee8888 could you take a look if QA Engineering have run the following 'git clean -d -q -f -x' that you mentioned in the pr #88 ?

**Comment by alee8888** [comment]
@clovisdasilvaneto yes we do run 'git clean -d -q -f -x' but we do not run  'ant all -Dclean.node.modules=true'. I tried to fetch this branch and build but am running into rebase issues. I was told that clean.node.modules will clean additional modules that are being ingored, do you think this is causing the errors?

Also, this is from the logs from the above run:
`From github-dev.liferay.com:liferay/liferay-jenkins-ee
 = [up to date]      master     -> master
Executing "git fetch --progress -v -f git@github-dev.liferay.com:liferay/liferay-jenkins-ee.git master:master" complete.
+ git checkout -f master
Switched to branch 'master'
+ git reset --hard ea5a1f0d7a2e49c44ec58f317f236bb491a51bad
HEAD is now at ea5a1f0 LRQA-38386 Blacklist updates
+ git checkout -f master-temp-1520289346779
Switched to branch 'master-temp-1520289346779'
+ git clean -d -f -x --exclude=git
+ git reset --hard
HEAD is now at ea5a1f0 LRQA-38386 Blacklist updates`

**Comment by clovisdasilvaneto** [comment]
@lee8888 probably yes, because the point the CI is breaking, is in the postinstall of node-sass@3.13.1, that is one of our dependencies, I'll rebase the code, and call you again here, is there ok for you?

**Comment by clovisdasilvaneto** [comment]
ci:close

**Pull request closed without merging**
