### PR TITLE
LPS-84039 No longer needed

### PR DESCRIPTION
**Pull request by leoadb**

### CODE REVIEW

**Comment by leoadb** [comment]
cc @hhuijser

**Comment by pedroqueiroz** [comment]
ci:test

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
Pull request submitted to https://github.com/rafaprax/liferay-portal/pull/842. [See changes here.](https://github.com/pedroqueiroz/liferay-portal/compare/4820886a0b03~1...4820886a0b03) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
Pull request submitted to https://github.com/rafaprax/liferay-portal/pull/847. [See changes here.](https://github.com/pedroqueiroz/liferay-portal/compare/2e1fd007f1d8~1...2e1fd007f1d8) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
Pull request submitted to https://github.com/rafaprax/liferay-portal/pull/851. [See changes here.](https://github.com/pedroqueiroz/liferay-portal/compare/61af8f7bfb95~2...61af8f7bfb95) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
