### PR TITLE
LPS-0 DO NOT MERGE Run all forms tests

### PR DESCRIPTION
**Pull request by rigosouza**

### CODE REVIEW

**Comment by rodrigo-e-c-souza** [comment]
Hi @pedroqueiroz94,

may you take a look on the changes in this PR? The issues here seems to be related to the changes except Forms#ChangeFieldType which is an expected error.

Thanks

**Comment by pedroqueiroz94** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by clovisdasilvaneto** [comment]
Guy's can you wait for some member from the frontend guild review this PR? Because there are some changes in javascript files wich we can review better 😁

**Comment by pedroqueiroz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
