### PR TITLE
[TECHNICAL-SUPPORT] LPS-83081

### PR DESCRIPTION
**Pull request by JosemariaMunoz**
https://issues.liferay.com/browse/LPS-83081

### CODE REVIEW

**Comment by JosemariaMunoz** [comment]
ci:test

**Comment by pedroqueiroz** [comment]
Hi, @JosemariaMunoz , thanks for the PR!

It looks good to me, but it is changing the Asset Publish code. Therefore, I will forward this to the WCM team.

Thanks!

**Comment by pedroqueiroz** [comment]
Pull request forwarded to https://github.com/ealonso/liferay-portal/pull/1837. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JosemariaMunoz** [comment]
Thanks a lot @pedroqueiroz !

**Pull request closed without merging**
