### PR TITLE
LPS-78779 Remove callback hell

### PR DESCRIPTION
**Pull request by alinedoleron**

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test

**Comment by pedroqueiroz** [comment]
ci:test

**Comment by rigosouza** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rigosouza** [comment]
Resent on: https://github.com/pedroqueiroz/liferay-portal/pull/132

**Pull request closed without merging**
