### PR TITLE
LPS-85353

### PR DESCRIPTION
**Pull request by crodriguezy**

### CODE REVIEW

**Comment by pedroqueiroz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/63141. [See changes here.](https://github.com/pedroqueiroz/liferay-portal/compare/342e971f40e6~1...342e971f40e6) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
Hey @crodriguezy ,

Thanks for the PR! :)

I've added a minor SF and sent to BChan.

**Comment by crodriguezy** [comment]
Thanks @pedroqueiroz !! :)

**Pull request closed without merging**
