### PR TITLE
LPS-71982 Remove gulp file and gulp dependencies from forms project to avoid node-sass dependency error

### PR DESCRIPTION
**Pull request by clovisdasilvaneto**

### CODE REVIEW

**Comment by clovisdasilvaneto** [comment]
c/ @brunobasto

**Comment by clovisdasilvaneto** [comment]
@vicnate5 Could you see if that tests above, which are failing is related with this PR?

**Comment by vicnate5** [comment]
@clovisdasilvaneto There are some unique failures on this pull (for FormsDataProvider and FormsRules). I can take a closer look today.

**Comment by pedroqueiroz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by vicnate5** [comment]
Reviewing now

**Comment by vicnate5** [comment]
@clovisdasilvaneto 

2 Regressions shown by the tests.

## Data Provider Dropdown
1. Add a Data Provider
2. View "Input" and "Output" **Type** field

Expected: Dropdown list
Actual: Cannot interact with the field

screenshot 2018-04-02 10 04 30

## Rule Summary
1. Add 2 text fields
2. Add a rule to show the second text field
3. Save rule
4. View rule Summary 

Expected: Full Summary
Actual: "If Field Text Field 1 Is equal to Value test show-x"

summarynotaccurate

**Comment by clovisdasilvaneto** [comment]
Thanks @vicnate5 I'll take a look in theses failures

**Comment by pedroqueiroz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
Sent to alinedoleron at https://github.com/alinedoleron/liferay-portal/pull/15.

**Pull request closed without merging**
