### PR TITLE
LPS-0 DO NOT MERGE Run all forms tests

### PR DESCRIPTION
**Pull request by clovisdasilvaneto**

### CODE REVIEW

**Comment by clovisdasilvaneto** [comment]
ci:test

**Comment by clovisdasilvaneto** [comment]
@rodrigo-e-c-souza , I don't know why the PR is falling, looks like that has some problems in the node-sass when the CI is going to deploy. @xbrianlee, may you guy take a look in this problem? In this PR we are adding the _liferay-npm-bundler_ in the date-field and numeric-field portlets, looks like the CI has some conflicts with this tool.

**Comment by xbrianlee** [comment]
Hi @clovisdasilvaneto, sorry for the late reply. I've asked @alee8888 to look into this issue since he's more familiar with npm than I am.

**Comment by clovisdasilvaneto** [comment]
Thank's @xbrianlee , I'll wait anxiously for the answer of @alee8888 😀

**Comment by alee8888** [comment]
@clovisdasilvaneto, these npm build errors are kind of out of QA's scope. We would need a developer's input on how to resolve this. @rafaprax @pedroqueiroz do you think you can help troubleshoot this?

**Comment by pedroqueiroz** [comment]
@clovisdasilvaneto , can you check this with @brunobasto ? Thanks!

**Comment by pedroqueiroz** [comment]
Hi, @alee8888 , how is it going? 

We have a question: do you guys clean your file system before running the portal tasks? 

According to @brunobasto , this kind of NPM issue usually can be fixed by deleting the node_modules directories before running `ant all`.

This would be our first approach, can you guys follow this up?

Thanks!

**Comment by pedroqueiroz** [comment]
@alee8888, do you have any news about this? Thanks!

**Comment by alee8888** [comment]
@pedroqueiroz Sorry I just confirmed with QA Engineering. We do run the following 'git clean -d -q -f -x' but we do not run 'ant all -Dclean.node.modules=true'. This might be the reason.

**Comment by pedroqueiroz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
Pull request submitted to https://github.com/pedroqueiroz94/liferay-portal/pull/undefined. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
Pull request submitted to https://github.com/pedroqueiroz/liferay-portal/pull/100. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
Hey @alee8888 , I have rebased this PR and resent to https://github.com/pedroqueiroz/liferay-portal/pull/100. I will try to run ci:test there again. Thanks for the follow up!

**Pull request closed without merging**
