### PR TITLE
LPS-84037 Using distinct to return just one record per structureId

### PR DESCRIPTION
**Pull request by achaparro**
Hi @pedroqueiroz,

I think that this change will save a lot of time for cases like the explained here:
https://issues.liferay.com/browse/LPS-84037

Could you review it?

Thanks.

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test

**Comment by rafaprax** [comment]
LGTM

**Comment by rafaprax** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
sent to BChan at https://github.com/brianchandotcom/liferay-portal/pull/61795.

Thx @achaparro

**Pull request closed without merging**
