### PR TITLE
LPS-78942 Only update the localizationMap if the value for that languageId is not empty

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by pedroqueiroz** [comment]
ci:test

**Comment by pedroqueiroz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
This is covered by poshi tests.

**Comment by pedroqueiroz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
Hey @rafaprax , we have an unique issue in this PR.

When we use a field nested in another field, a JS error is thrown on submission:

```
Uncaught TypeError: parent.addAvailableLanguageIds is not a function
    at component.toJSON (ddm_form.js?browserId=other&minifierType=&languageId=en_US&b=7100&t=1521767486070:773)
    at YUI.<anonymous> (array-invoke.js:32)
    at Array.forEach (<anonymous>)
    at Function.YArray.each.YArray.forEach (aui.js:2522)
    at Function.Y.Array.invoke (array-invoke.js:30)
    at component.toJSON (ddm_form.js?browserId=other&minifierType=&languageId=en_US&b=7100&t=1521767486070:779)
    at YUI.<anonymous> (array-invoke.js:32)
    at Array.forEach (<anonymous>)
    at Function.YArray.each.YArray.forEach (aui.js:2522)
    at Function.Y.Array.invoke (array-invoke.js:30)
```

Can you check this? Thanks!

**Comment by rafaprax** [comment]
ci:test

**Comment by pedroqueiroz** [comment]
ci:test

**Comment by pedroqueiroz** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/56641. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
