### PR TITLE
LPS-77053 Adjusting poshi path

### PR DESCRIPTION
**Pull request by rigosouza**

### CODE REVIEW

**Comment by rigosouza** [comment]
ci:test

**Comment by brunobasto** [comment]
LGTM

**Comment by pedroqueiroz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/57262. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
