### PR TITLE
LPS-80810 + LPS-80964 - Security audit

### PR DESCRIPTION
**Pull request by topolik**
Hi Pedro,

* https://issues.liferay.com/browse/LPS-80810 DDM,DDL+Forms
* https://issues.liferay.com/browse/LPS-80964 Polls

There are still XSS issues but these looks from come from JS which I'm not that good at. Please see https://issues.liferay.com/browse/LPS-80966

Can you please peer-review and send to Brian if OK?

Thanks!

/cc @rafaprax

### CODE REVIEW

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by topolik** [comment]
ci:reopen

**Comment by topolik** [comment]
ci:test:relevant (added new commit - fixed semver)

**Comment by topolik** [comment]
The functional tests shows errors but I cannot reproduce it locally. Do you guys know what's wrong?

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by rafaprax** [comment]
LGTM

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/58825. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
