### PR TITLE
LPS-78206 Auto SF.

### PR DESCRIPTION
**Pull request by natocesarrego**

### CODE REVIEW

**Comment by rolandpakai** [comment]
Hi @pedroqueiroz,

could you please take a look at this PR?

Many thanks, Roland

**Comment by pedroqueiroz** [comment]
Hey @rolandpakai , sure! This is the next task in my Queue. Thanks!

**Comment by pedroqueiroz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/56115. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
@rafaprax , test not needed since we don't have JS Unit Tests.

**Pull request closed without merging**
