### PR TITLE
LPS-80970 Adds listeners to non-navigating actions in ddl

### PR DESCRIPTION
**Pull request by carloslancha**

### CODE REVIEW

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
Hey @hhuijser this SF error only happens in CI, I don't get it in local neither with `gradlew formatSource` nor `ant format-source-current-branch`.  Just to let you know. Thanks!

**Comment by carloslancha** [comment]
ci:reopen

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/58657. [See changes here.](https://github.com/pedroqueiroz/liferay-portal/compare/0259764bbbbd~3...0259764bbbbd) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
Thanks, @carloslancha ! :)

**Comment by hhuijser** [comment]
@carloslancha I'll look into that

**Comment by hhuijser** [comment]
Hey @carloslancha 

It works fine on my end.
This is a check in SF that was added about a month ago.

Just checking... you have ran `ant all` since that change (April 18th)?

**Comment by carloslancha** [comment]
@hhuijser yes, I ran `ant all` yesterday. I'll let you know if it happens again, thx!

**Comment by pedroqueiroz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/58751. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
