### PR TITLE
LPS-78433 SF

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by MichaelPrigge** [comment]
ci:test

**Comment by MichaelPrigge** [comment]
ci:reopen

**Comment by pedroqueiroz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
Pull request submitted to https://github.com/pedroqueiroz/liferay-portal/pull/115. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
