### PR TITLE
LPS-83081 Auto

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
Hey @JosemariaMunoz @pedroqueiroz,

I've added a new method into DDMStructure service to get structures including ancestors or not, like we do in **fetchStructure**. If everything looks good to you please sent it to Brian.

Regards,
Eudaldo.

**Comment by JosemariaMunoz** [comment]
Hey @ealonso,
It's looks good to me, thanks!
@pedroqueiroz, if is ok for you, and according to Eudaldo's comment, please send it to Brian.
Thanks!

**Comment by pedroqueiroz** [comment]
ci:test:sf

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/61254. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
Thanks for the PR, guys! :) @ealonso @JosemariaMunoz

**Comment by JosemariaMunoz** [comment]
Thanks both! @pedroqueiroz @ealonso

**Pull request closed without merging**
