### PR TITLE
LPS-77053 Modified path to be according to new pagination markup

### PR DESCRIPTION
**Pull request by rigosouza**

### CODE REVIEW

**Comment by rigosouza** [comment]
ci:test

**Comment by vicnate5** [comment]
ci:test

**Comment by vicnate5** [comment]
ci:retest

**Comment by pedroqueiroz** [comment]
ci:test

**Comment by rigosouza** [comment]
ci:test

**Comment by rigosouza** [comment]
ci:test

**Comment by pedroqueiroz** [comment]
ci:test

**Comment by vicnate5** [comment]
@rigosouza 2 tests still need to be update for the pages change

FormsJumpToPage#ViewRuleAfterPageNameChange
Forms#DeletePages

Bundle is attached!

**Comment by rigosouza** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rigosouza** [comment]
Resent on https://github.com/pedroqueiroz/liferay-portal/pull/124

**Pull request closed without merging**
