### PR TITLE
LPS-000 Read the readOnly property in the context processor

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by rafaprax** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/61159. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
