### PR TITLE
LPS-78974 Get localized image description

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:test

**Comment by pavel-savinov** [comment]
ci:reopen

**Comment by pedroqueiroz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
Pull request submitted to https://github.com/rafaprax/liferay-portal/pull/641. [See changes here.](https://github.com/pedroqueiroz/liferay-portal/compare/4e37e397b0a3~1...4e37e397b0a3) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
