### PR TITLE
[TECHNICAL-SUPPORT] LPS-86565

### PR DESCRIPTION
**Pull request by JosemariaMunoz**
https://issues.liferay.com/browse/LPS-86565
Hi @pedroqueiroz !
Please let me know if you need anything.
Thanks!

### CODE REVIEW

**Comment by JosemariaMunoz** [comment]
ci:test

**Comment by JosemariaMunoz** [comment]
ci:reopen

**Comment by JosemariaMunoz** [comment]
Hi @pedroqueiroz,

Sorry, I didn't get this failures when I test twice in my own git account: https://github.com/JosemariaMunoz/liferay-portal/pull/40
Otherwise I will ask you directly about this or even to the SME.

I realize that failed test is because 'assertEquals' say that "1,2" in Brazilian has to be "1,2" but I think this is wrong, like in english. This commit just apply java.text.NumberFormat parse, based on locale, to the current string value. Before that commit, value always was 0 but now "1,2", when using java.text.NumberFormat parsing, is parsed to 12 (In languages with a period (.) as decimal separator). On the other hand when decimal separator is a comma (,), "1,2" is parsed well to "1,2".

I mean, with this solution, the result is the real parsing of java.text.NumberFormat for each language, Do you think this is right? If do you prefer, I can ask to the SME.

Thanks a lot!

**Comment by pedroqueiroz** [comment]
Hey @JosemariaMunoz , actually this test also failed in your own account as well. You can check them on this link, as showed on the screenshot:

screen shot 2018-10-29 at 5 00 17 pm

It's tricky, but it's there. :)

In Brazilian Portuguese, "1,2" means "1.2", so the tests seem to be ok. Can you investigate why the NumberFormat parser is not taking the locale into account?

Thanks a lot!

**Comment by JosemariaMunoz** [comment]
Ok @pedroqueiroz, 
It's weird because It wasn't failed into '**Failures unique to this pull:**' in my account so, if is not unique to this pull, is because it was failing before, isn't it?

Anyway, you are right, [this test code](https://github.com/liferay/liferay-portal/blob/master/modules/apps/dynamic-data-mapping/dynamic-data-mapping-test/src/test/java/com/liferay/dynamic/data/mapping/render/DDMFormFieldValueRendererTest.java#L178-L181) should to work fine.

Thanks a lot for your help and sorry for the confusion, I will think again about this.

**Comment by pedroqueiroz** [comment]
Hey @JosemariaMunoz , the CI can be really tricky sometimes.

Actually, the failure was indeed unique to your pull, you did not see because the message gets truncated, as you can see here:

screen shot 2018-10-30 at 9 36 43 am

So it's always a good practice to check the failed jobs on the top of the message when the bot truncates the rest of the errors.

Does it make sense? :)

Thanks!

**Comment by JosemariaMunoz** [comment]
Yeah, good point, make all of the sense of the world (like we said in spanish) hahahaha

Thanks again @pedroqueiroz , you help me a lot!

**Comment by pedroqueiroz** [comment]
That's awesome, @JosemariaMunoz !! ahahaha

We have that expression in Portuguese too! :P 

We're here to help! :)

**Pull request closed without merging**
