### PR TITLE
LPS-62598 Add character limit in form title and description

### PR DESCRIPTION
**Pull request by clovisdasilvaneto**

### CODE REVIEW

**Comment by pedroqueiroz** [comment]
ci:test

**Comment by pedroqueiroz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
ci:retest

**Comment by pedroqueiroz** [comment]
@clovisdasilvaneto , according com @brunobasto this PR might need some refactor. Can you talk to him and see what would those be?

Also, can you please talk to Jadson and check the character limits for each field?

Thanks!

**Comment by clovisdasilvaneto** [comment]
re-sendend for rafaprax in: https://github.com/rafaprax/liferay-portal/pull/424

**Pull request closed without merging**
