### PR TITLE
LPS-77053 Modified path to be according to new pagination markup

### PR DESCRIPTION
**Pull request by rigosouza**

### CODE REVIEW

**Comment by rigosouza** [comment]
ci:test

**Comment by rigosouza** [comment]
ci:test

**Comment by pedroqueiroz** [comment]
ci:test

**Comment by pedroqueiroz** [comment]
ci:test

**Comment by pedroqueiroz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
Pull request submitted to https://github.com/rafaprax/liferay-portal/pull/455. [See changes here.](https://github.com/pedroqueiroz/liferay-portal/compare/290d91b130ac~1...290d91b130ac) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
