### PR TITLE
LPS-77053 Adjust wizard for form builder

### PR DESCRIPTION
**Pull request by clovisdasilvaneto**

### CODE REVIEW

**Comment by clovisdasilvaneto** [comment]
ci:test

**Comment by clovisdasilvaneto** [comment]
ci:stop

**Comment by clovisdasilvaneto** [comment]
ci:test

**Comment by rigosouza** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rigosouza** [comment]
Resent on https://github.com/pedroqueiroz/liferay-portal/pull/118

**Pull request closed without merging**
