### PR TITLE
LPS-78556 Use associated input localized instead of deprecated translation manager

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:test

**Comment by pedroqueiroz** [comment]
ci:test

**Comment by pavel-savinov** [comment]
It seems that fails have nothing to do with the PR...

**Comment by pedroqueiroz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/56212. [See changes here.](https://github.com/pedroqueiroz/liferay-portal/compare/aa45a29014b2~1...aa45a29014b2) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
No test needed, since we don't have JS Unit Tests.

**Pull request closed without merging**
