### PR TITLE
LPS-77057 Buttons in Modal isn't in new lexicon version

### PR DESCRIPTION
**Pull request by clovisdasilvaneto**

### CODE REVIEW

**Comment by clovisdasilvaneto** [comment]
ci:test

**Comment by pedroqueiroz** [comment]
ci:retest

**Comment by diegonvs** [comment]
ci:retest

**Comment by pedroqueiroz** [comment]
ci:retest

**Comment by diegonvs** [comment]
ci:retest

**Comment by pedroqueiroz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/56214. [See changes here.](https://github.com/pedroqueiroz/liferay-portal/compare/2dd0917d00e5~1...2dd0917d00e5) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
No test needed, since we don't have JS Unit tests.

**Pull request closed without merging**
