### PR TITLE
[TECHNICAL-SUPPORT] LPS-81935

### PR DESCRIPTION
**Pull request by JosemariaMunoz**
https://issues.liferay.com/browse/LPS-81935

Hey @pedroqueiroz,

This PR is related to https://github.com/rafaprax/liferay-portal/pull/694 but with integration test.

Let me know if I can help with anything more!

Thanks!

### CODE REVIEW

**Comment by JosemariaMunoz** [comment]
ci:test

**Comment by JosemariaMunoz** [comment]
ci:reopen

**Comment by JosemariaMunoz** [comment]
Hi @pedroqueiroz ,
I don't understand what is happening because I run this tests without failures in my local and even in my own git account: https://github.com/JosemariaMunoz/liferay-portal/pull/32#issuecomment-397104660
I will review this code...

**Comment by JosemariaMunoz** [comment]
ci:retest

**Comment by pedroqueiroz** [comment]
ci:test:sf

**Comment by pedroqueiroz** [comment]
ci:test:relevant

**Comment by pedroqueiroz** [comment]
Hey @JosemariaMunoz , don't worry about it. I talked to Máté and he said it was a staging problem, and he has reverted it here: https://github.com/liferay/liferay-portal/compare/7ad3b8b...0ec696f .

I will just wait for `ci:test:relevant` results in order to move this forward.

Thanks a lot for your PR!

**Comment by pedroqueiroz** [comment]
Pull request forwarded to https://github.com/brianchandotcom/liferay-portal/pull/60296. [See changes here.](https://github.com/pedroqueiroz/liferay-portal/compare/a5c6fc7ff060~1...a5c6fc7ff060) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JosemariaMunoz** [comment]
Great!! Thanks a lot for your help @pedroqueiroz !

**Pull request closed without merging**
