### PR TITLE
LPS-0 DO NOT MERGE Run all forms tests

### PR DESCRIPTION
**Pull request by rafaprax**

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test

**Comment by pedroqueiroz** [comment]
@rafaprax LGTM ! :) Just add the export back, so we don't break anything. Thanks!

**Comment by pedroqueiroz** [comment]
ci:test

**Comment by pedroqueiroz** [comment]
ci:test

**Comment by pedroqueiroz** [comment]
ci:test

**Comment by rafaprax** [comment]
ci:test

**Comment by pedroqueiroz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rafaprax** [comment]
ci:test

**Comment by pedroqueiroz** [comment]
Pull request submitted to https://github.com/pedroqueiroz/liferay-portal/pull/130. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/56844. [See changes here.](https://github.com/pedroqueiroz/liferay-portal/compare/bca03e3a813f~1...bca03e3a813f) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
