### PR TITLE
LPS-81978 SF

### PR DESCRIPTION
**Pull request by matuzalemsteles**

### CODE REVIEW

**Comment by matuzalemsteles** [comment]
hey @pedroqueiroz, This will work when https://github.com/liferay/clay/pull/982 is merged and when have a release of Clay on the master.

**Comment by pedroqueiroz** [comment]
Thanks, @matuzalemsteles ! :) Do you know when this release will be made?

**Comment by pedroqueiroz** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by pedroqueiroz** [comment]
Pull request submitted to https://github.com/rafaprax/liferay-portal/pull/717. [See changes here.](https://github.com/pedroqueiroz/liferay-portal/compare/739fa895b09e~2...739fa895b09e) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
