### PR TITLE
LPS-78779 Adjusting path

### PR DESCRIPTION
**Pull request by rigosouza**

### CODE REVIEW

**Comment by rigosouza** [comment]
ci:test

**Comment by vicnate5** [comment]
LGTM. Just needs rebase.

**Comment by alinedoleron** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by alinedoleron** [comment]
rebased and resent to https://github.com/pedroqueiroz/liferay-portal/pull/133

**Comment by alinedoleron** [comment]
ci:close

**Pull request closed without merging**
